services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.dashboard=true"
      - "--api.insecure=true"  # Only for local/dev
    ports:
      - "80:80"
    networks:
      - internal_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock



  portainer_agent:
    image: portainer/agent:latest
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"  # Insecure if exposed to all IPs!
    networks:
      - internal_backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  internal_backend:
    name: internal_backend
    driver: bridge
